### PR TITLE
Convert --param arguments to option directives.

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by davidmalcolm** [comment]
No unit test? :)

Also, looking at https://github.com/marxin/texi2rst-generated/commit/5e61c544474367aec39f470e541f5552386da9d7, the first part of this hunk looks wrong to me:
```
@@ -3427,15 +3540,25 @@ of :samp:`{name}` are recognized for all targets:
   generation.
 
   The default is 30% + 70% * (RAM/1GB) with an upper bound of 100% when
-  RAM >= 1GB.  If ``getrlimit`` is available, the notion of 'RAM' is
-  the smallest of actual RAM and ``RLIMIT_DATA`` or ``RLIMIT_AS``.  If
+  RAM >= 1GB.  If 
+  .. option:: getrlimit
+
+   is available, the notion of 'RAM' is
+  the smallest of actual RAM and 
+  .. option:: RLIMIT_DATA
+
+   or 
+  .. option:: RLIMIT_AS
+
+  .  If
   GCC is not able to calculate RAM on a particular platform, the lower
   bound of 30% is used.  Setting this parameter and
   ggc-min-heapsize to zero causes a full collection to occur at
   every opportunity.  This is extremely slow, but can be useful for
   debugging.
 
-``ggc-min-heapsize``
+.. option:: ggc-min-heapsize
+
   Minimum size of the garbage collector's heap before it begins bothering
   to collect garbage.  The first collection occurs after the heap expands
   by ggc-min-expand % beyond ggc-min-heapsize.  Again,

```

**Comment by davidmalcolm** [comment]
I think it's erroneously doing the fixup on all descendents, rather than direct children, perhaps?

**Comment by marxin** [comment]
> No unit test? :)

It's not easy to copy such huge xml block :)

> 
> Also, looking at [marxin/texi2rst-generated@5e61c54](https://github.com/marxin/texi2rst-generated/commit/5e61c544474367aec39f470e541f5552386da9d7), the first part of this hunk looks wrong to me:

Yes, it's wrong. Actually they are wrapped in `<item>` element and it should be fixed now.

**Comment by marxin** [comment]
And I've just made one GCC upstream fix: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=ca7d451d985b31a0b593b50115971e70ae0767da

**Pull request merged**
